.gitignore
package-lock.json
src/api/contacts/controller.js
src/api/contacts/index.js
src/api/router.js
src/helpers/constants.js
src/helpers/databaseTransaction.js
src/schema/contact.js

397737 - MongoDB CRUD transactions

---

src/services/powerapps/auth.js

392804 - Test commit

---

src/api/dataverse/controller.js
src/api/dataverse/index.js
src/helpers/constants.js
src/schema/organizationNContact.js
src/services/powerapps/auth.js

392804 - Saving organization and contact data

---

src/api/crud-transaction/controllers/create-controller.js
src/api/crud-transaction/controllers/list-controller.js
src/api/crud-transaction/controllers/read-controller.js
src/api/crud-transaction/controllers/update-controller.js
src/api/crud-transaction/index.js
src/api/router.js
src/config/index.js
src/helpers/constants.js
src/helpers/databaseTransaction.js
src/helpers/proxy-agent.js
src/schema/contacts.js
src/schema/organizations.js

Form Submission

---

src/api/dataverse/controller.js
src/api/dataverse/index.js
src/helpers/constants.js
src/schema/developmentSite.js

added code for saving development site details

---

src/api/dataverse/controller.js

printing config

---

src/services/powerapps/auth.js

printing whole error

---

src/services/powerapps/auth.js

Fixing the proxy while authenticating the azure app

---

src/services/powerapps/auth.js

Overriding MSAL configuration to use proxy

---

src/api/dataverse/controller.js

returning the response

---

src/api/dataverse/controller.js
src/services/powerapps/auth.js

Using the proxyFetch while getting the azure token

---

src/helpers/proxy-fetch.js
src/services/powerapps/auth.js

await for the response

---

src/helpers/constants.js
src/schema/organizations.js
src/schema/upload.js

Fixing the entity validation issue

---

src/api/dataverse/controller.js

added code for adding dev site

---

src/api/dataverse/controller.js
src/schema/developmentSite.js

added code for development site table

---

src/api/dataverse/controller.js
src/helpers/constants.js
src/schema/developmentSite.js

modified columns for dev site table

---

src/api/dataverse/controller.js

returning error

---

src/api/dataverse/controller.js

added log statement

---

src/api/dataverse/helpers/process-options.js
src/helpers/fetchProxyWrapper.js
src/services/powerapps/dataverse.js

Error handling

---

src/helpers/fetchProxyWrapper.js

Disabling the proxy

---

src/api/dataverse/controller.js
src/helpers/fetchProxyWrapper.js

Enabling the proxy

---

src/api/dataverse/controller.js

Reverting the changes, & fixing the label issue

---

src/api/dataverse/controller.js
src/schema/developmentSite.js

modified payload for dev site

---

src/api/dataverse/controller.js
src/schema/developmentSite.js

added folderPath

---

src/api/crud-transaction/controllers/create-controller.js
src/helpers/build-error-details.js
src/helpers/constants.js
src/schema/organizations.js

Fixing the payload for organization

---

src/api/crud-transaction/controllers/update-controller.js
src/helpers/constants.js
src/schema/contacts.js
src/schema/organizations.js
src/schema/upload.js

Fixing the issues

---

src/api/sharepoint/controllers/index-controller.js

Checking the error

---

src/api/sharepoint/controllers/index-controller.js
src/helpers/fetchProxyWrapper.js
src/services/powerapps/dataverse.js

MMoving the files to sharepoint

---

src/services/powerapps/dataverse.js

Adding duplex value

---

src/api/dataverse/controller.js

Fixing the development site saving controller code

---

src/api/dataverse/controller.js
src/services/powerapps/auth.js

Fixing the token generation issue

---

src/api/dataverse/controller.js
src/helpers/constants.js
src/schema/developmentSite.js

Fixing the development site payload issue

---

src/api/contacts/controller.js
src/api/crud-transaction/controllers/create-controller.js
src/api/crud-transaction/controllers/list-controller.js
src/api/crud-transaction/controllers/read-controller.js
src/api/crud-transaction/controllers/update-controller.js
src/api/dataverse/controller.js
src/api/dataverse/helpers/nested-property-value.js
src/api/dataverse/helpers/process-options.js
src/api/job/controllers/submission-job.js
src/helpers/build-error-details.js
src/helpers/database-transaction.js
src/helpers/fetchProxyWrapper.js
src/helpers/jobs/job-manager.js
src/helpers/jobs/schedule-jobs.js
src/jobs/fetch-submission.js
src/services/powerapps/auth.js
src/services/powerapps/authProxyClient.js
src/services/powerapps/dataverse.js

Added the doc comments for each file

---

src/services/powerapps/auth.js

Adding the scope for sharepoint access

---

src/services/powerapps/auth.js

Reverting the scope changes

---

src/services/powerapps/auth.js
src/services/powerapps/dataverse.js

SharePoint access token

---

src/api/dataverse/controller.js
src/api/dataverse/index.js

Added controller for SharePoint token

---

src/api/sharepoint/controllers/index-controller.js
src/api/sharepoint/helpers/stream-to-buffer.js

Fixing the stream to buffer of S3 file

---

src/helpers/fetchProxyWrapper.js

Change in the error message

---

src/api/sharepoint/controllers/index-controller.js
src/services/powerapps/dataverse.js

SharePoint test

---

src/api/sharepoint/controllers/index-controller.js

added log statement for reading document from MongoDB

---

src/api/sharepoint/controllers/index-controller.js

commented all code for printing logs

---

src/api/sharepoint/controllers/index-controller.js

commented uploadToSP

---

src/api/sharepoint/controllers/index-controller.js
src/services/powerapps/dataverse.js

added a method for Logic App invocation

---

src/api/sharepoint/controllers/index-controller.js

added a response for Logic App

---

src/api/sharepoint/controllers/index-controller.js
src/helpers/fetchProxyWrapper.js
src/services/powerapps/dataverse.js

added comments

---

src/services/powerapps/dataverse.js

added response.body as comment

---

src/helpers/fetchProxyWrapper.js
src/helpers/proxy-fetch.js
src/services/powerapps/dataverse.js

added empty object as param to proxyWrapper

---

src/helpers/fetchProxyWrapper.js
src/services/powerapps/dataverse.js

added different method for proxyFetch

---

src/helpers/fetchProxyWrapper.js

create another method for handling response

---

src/helpers/proxy-fetch.js

added some comments

---

src/helpers/fetchProxyWrapper.js

added log statement for response

---

src/helpers/proxy-fetch.js

passing blank obj as options

---

src/helpers/fetchProxyWrapper.js
src/helpers/proxy-fetch.js

adding log statement

---

src/helpers/proxy-fetch.js

kept only proxy call

---

src/api/sharepoint/controllers/index-controller.js

added code for uploading to SP

---

src/api/sharepoint/controllers/index-controller.js

modified ulpoadURl

---

src/api/sharepoint/controllers/index-controller.js
src/services/powerapps/dataverse.js

changed call to GET

---

src/services/powerapps/dataverse.js

removed body

---

src/services/powerapps/dataverse.js

printing json input

---

src/api/sharepoint/controllers/index-controller.js

pointed Logic App URL to workflow2

---

src/api/sharepoint/controllers/index-controller.js

modified url to new workflow

---

src/services/powerapps/dataverse.js

made content type as json instead of octet-stream

---

src/services/powerapps/dataverse.js

added content type as json

---

src/services/powerapps/dataverse.js

changed body to string

---

src/services/powerapps/dataverse.js

removed duplex from payload

---

src/helpers/fetchProxyWrapper.js

changed response to text from json
